name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치 푸시 시 자동 배포

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus
        run: npm run build

      - name: Deploy to GitHub Pages (Option 1: USE_SSH)
        run: USE_SSH=true npm run deploy